AWSTemplateFormatVersion: '2010-09-09'
Description: 'Static Website with S3, CloudFront, and Route53'

Parameters:
  DomainName:
    Type: String
    Default: 'resume.cloudkruser.com'
  SubDomainName:
    Type: String
    Default: 'www.resume.cloudkruser.com'
  BucketName:
    Type: String
    Default: 'cloud-kruser-static-website'

Resources:

  # Route53 Hosted Zone
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  # # SSL Certificate
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Ref SubDomainName
      CertificateTransparencyLoggingPreference: ENABLED
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZone
        - DomainName: !Ref SubDomainName
          HostedZoneId: !Ref HostedZone

  # DNS Record
  DNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: CloudKruser Static Website DNS Records
      RecordSets:
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            DNSName: !GetAtt Distribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2 
            EvaluateTargetHealth: false
        # - Name: !Ref DomainName
        #   Type: AAAA
        #   AliasTarget:
        #     DNSName: !GetAtt Distribution.DomainName
        #     HostedZoneId: Z2FDTNDATAQYW2 
        #     EvaluateTargetHealth: false

  # S3 Bucket
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Origin Access Control
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${BucketName}-OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            Id: S3Origin
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
          - !Ref SubDomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          Compress: true
        PriceClass: PriceClass_100

  # S3 Bucket Policy
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub '${WebsiteBucket.Arn}/*'
            Condition:
              StringLike:
                'aws:SourceArn': !Sub 'arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${Distribution}'
          - Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${WebsiteBucket.Arn}/*'
              - !GetAtt WebsiteBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          - Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${WebsiteBucket.Arn}/*'
              - !GetAtt WebsiteBucket.Arn
            Condition:
              NumericLessThan:
                's3:TlsVersion': '1.2'

Outputs:
  WebsiteURL:
    Value: !Sub 'https://${DomainName}'
  DistributionId:
    Value: !Ref Distribution
  BucketName:
    Value: !Ref WebsiteBucket